### ISSUE TITLE
How to install on nestJS

### ISSUE THREAD

**Issue by tiagov02** [kael-shipman/swagger-ui-plugins#4]
I tried to install on nestJS the pluggin swagger-ui-plugin-hierarchical-tags and I cant run. That error occurs:

TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at C:\Users\Tiago Viana\Desktop\DEV-IPVC_Final\webservices_ipvc\node_modules\swagger-ui-plugin-hierarchical-tags\build\index.js:6:14895
    at Module.<anonymous> (C:\Users\Tiago Viana\Desktop\DEV-IPVC_Final\webservices_ipvc\node_modules\swagger-ui-plugin-hierarchical-tags\build\index.js:6:15172)
    at Module.<anonymous> (C:\Users\Tiago Viana\Desktop\DEV-IPVC_Final\webservices_ipvc\node_modules\swagger-ui-plugin-hierarchical-tags\build\index.js:6:15300)
    at r (C:\Users\Tiago Viana\Desktop\DEV-IPVC_Final\webservices_ipvc\node_modules\swagger-ui-plugin-hierarchical-tags\build\index.js:1:110)
    at C:\Users\Tiago Viana\Desktop\DEV-IPVC_Final\webservices_ipvc\node_modules\swagger-ui-plugin-hierarchical-tags\build\index.js:1:902
    at Object.<anonymous> (C:\Users\Tiago Viana\Desktop\DEV-IPVC_Final\webservices_ipvc\node_modules\swagger-ui-plugin-hierarchical-tags\build\index.js:1:912)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)

**Comment by tiagov02** [comment]
Solved. I just copied

**Comment by vinodh-r** [comment]
@tiagov02 I am facing the same issue. Can you provide some details how you resolved it? Thanks!

**Comment by tiagov02** [comment]
I change directly on the library
### After Start
After Start you need to change this var in the file ```node_modules/@nestjs/swagger/dist/swagger-ui/constants.js```
After you do that you need to restart the project.

```js
exports.htmlTemplateString = `
<!doctype html>
<html>
  <head>
    <!-- Load Swagger UI -->
    <script src="https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js"></script> 

    <!-- Load the HierarchicalTags Plugin -->
    <script src="https://unpkg.com/swagger-ui-plugin-hierarchical-tags"></script>

    <!-- Load styles -->
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist/swagger-ui.css" />

    <script>
      window.onload = function() {
        SwaggerUIBundle({
          url: "/api-json",
          dom_id: "#swagger",
          plugins: [
            HierarchicalTagsPlugin
          ]
        })
      }
    </script>
  </head>
  <body>
    <div id="swagger"></div>
  </body>
</html>
`;
```

Then you restart

**Comment by vinodh-r** [comment]
Thanks @tiagov02 ! That helps out a lot.
